version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - '5440:5432'
    volumes:
      - postgres_database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_database_data: {}
